### ISSUE TITLE
Warnings from help files

### ISSUE THREAD

**Issue by pauldwkirk** [HGray384/pcaNet#12]
When installing, we get the following warnings:

> Warning: /private/var/folders/sn/0b9d9phd6wj3_vc342wylhph0000gp/T/Rtmp8H4zLt/devtools162f723a2082d/pauldwkirk-ppcaNet-30f79bf493302fd8dce484b157e411c67783b6b6/man/ppcaNet-package.Rd:27: All text must be in a section
> Warning: /private/var/folders/sn/0b9d9phd6wj3_vc342wylhph0000gp/T/Rtmp8H4zLt/devtools162f723a2082d/pauldwkirk-ppcaNet-30f79bf493302fd8dce484b157e411c67783b6b6/man/ppcaNet-package.Rd:28: All text must be in a section

**Comment by HGray384** [comment]
issue fixed!
