### ISSUE TITLE
Warnings when running pcapM

### ISSUE THREAD

**Issue by pauldwkirk** [HGray384/pcaNet#13]
> Warning messages:
> 1: In if (!scale %in% c("none", "pareto", "vector", "uv")) { :
>   the condition has length > 1 and only the first element will be used
> 2: In if (scale == "none") { :
>   the condition has length > 1 and only the first element will be used
> 3: In if (scale == "uv") { :
>   the condition has length > 1 and only the first element will be used
> 4: In if (scale == "pareto") { :
>   the condition has length > 1 and only the first element will be used
> 5: In if (scale == "vector") { :
>   the condition has length > 1 and only the first element will be used
> 6: In if (scaled(x)) cat("Data was scaled before running PCA \n") else cat("Data was NOT scaled before running PCA \n") :
>   the condition has length > 1 and only the first element will be used

**Comment by HGray384** [comment]
42788b375d34569c250ccc667d32324ce4bcd121 fixed here
