### ISSUE TITLE
failed installation on mac

### ISSUE THREAD

**Issue by HGray384** [HGray384/pcaNet#15]

**Comment by pauldwkirk** [comment]
Fixes the problem (for me, at least): https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

**Comment by pauldwkirk** [comment]
@HGray384 - if this also works for you, I will close the issue

**Comment by HGray384** [comment]
@pauldwkirk installation works for me. I get some warnings but we can talk about those.
